services:
  mongodb:
    image: mongo:latest
    container_name: ai-proctor-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - ai_proctor_net

  backend:
    build: ./backend
    container_name: ai-proctor-backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    env_file:
      - .env
    networks:
      - ai_proctor_net

  frontend:
    build: ./frontend
    container_name: ai-proctor-frontend
    ports:
      - "3002:80" # Map host port 3002 to Nginx container port 80
    depends_on:
      - backend
    networks:
      - ai_proctor_net

networks:
  ai_proctor_net:
    driver: bridge

volumes:
  mongodb_data:
    driver: local 